# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-03 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('owner', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('car_model', models.CharField(max_length=70)),
                ('car_type', models.CharField(max_length=70)),
                ('year', models.IntegerField()),
                ('registration_indicator', models.CharField(max_length=70)),
                ('number_of_seats', models.IntegerField()),
                ('colour', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.Brand')),
            ],
        ),
    ]
