# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-06 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0003_car_is_advertised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(max_length=256),
        ),
    ]
