# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-06 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0004_auto_20180806_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration_indicator',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used vehicle'), ('R', 'Re-registrations'), ('S', 'Scratch-built')], default='N', max_length=20),
        ),
    ]
