# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-13 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0018_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='creation_date',
        ),
    ]
