# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-14 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0022_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='car',
        ),
        migrations.AddField(
            model_name='purchase',
            name='car_colour',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='car_info',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
