# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0029_auto_20180815_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_public_key',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_secret_key',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
