# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0031_auto_20180815_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MarketApp.Brand'),
        ),
    ]
