# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0032_auto_20180816_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.Brand'),
        ),
    ]
