# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0034_auto_20180816_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_public_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_secret_key',
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_user_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
