# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-17 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0036_auto_20180816_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='colour',
            field=models.CharField(choices=[('#00ffff', 'aqua'), ('#000000', 'black'), ('#0000ff', 'blue'), ('#ff00ff', 'fuchsia'), ('#008000', 'green'), ('#808080', 'gray'), ('#00ff00', 'lime'), ('#800000', 'maroon'), ('#000080', 'navy'), ('#808000', 'olive'), ('#800080', 'purple'), ('#ff0000', 'red'), ('#c0c0c0', 'silver'), ('#008080', 'teal'), ('#ffffff', 'white'), ('#ffff00', 'yellow')], max_length=70),
        ),
    ]
