# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-28 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0040_auto_20180828_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creation_date',
            new_name='date',
        ),
    ]
