# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-29 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0041_auto_20180828_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=150, unique=True),
        ),
    ]
