# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-07 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0006_auto_20180806_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
