# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0015_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
