# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-14 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0023_auto_20180814_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='car_colour',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='car_info',
        ),
        migrations.AddField(
            model_name='purchase',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_app.Car'),
        ),
    ]
