# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-15 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0028_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='stock_count',
            field=models.IntegerField(default=1),
        ),
    ]
