# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-28 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0039_auto_20180820_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='owner',
            new_name='user',
        ),
    ]
